// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ASLearn",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ASLearn",
            targets: ["AppModule"],
            bundleIdentifier: "com.karandeepsingh.ASLearn",
            teamIdentifier: "U57LJ9Q756",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown()
            ],
            capabilities: [
                .camera(purposeString: "ASLearn uses the camera to recognise hand gestures and translate them to text.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
